// import Image from "next/image";
import BlogCategory from "@/components/pages/blog/BlogCategory/BlogCategory";
import styles from "./page.module.scss";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Blog",
	description: "Generated by create next app",
};

export default function Home() {
	return (
		<>
			<main className={styles.main}>
				<BlogCategory />
			</main>
		</>
	);
}
